### ISSUE TITLE
Allow compiling addr without depending on openssl

### ISSUE THREAD

**Issue by leshow** [addr-rs/addr#5]
The sub-crates of addr appear to have features to disable fetching of remote lists, but addr doesn't allow a 'pass-through' of these features. It would be nice to be able to disable the remote list from `addr`. 

Additionally, I don't suppose theres a way to build the list at runtime?

**Comment by rushmorem** [comment]
Now fixed. The latest version now only depends on `psl` for the list and one other optional dependency on `serde` (https://crates.io/crates/addr/0.5.1/dependencies). It's also now `no_std`.

> Additionally, I don't suppose theres a way to build the list at runtime?

`addr`, through `psl` uses an embedded list compiled to native Rust code for maximum performance and correctness. This list is no longer downloaded at compile time, so no other dependencies are pulled in except `psl` (which has no dependencies except for the optional `serde` feature).
