### ISSUE TITLE
Docs fail to build on docs.rs

### ISSUE THREAD

**Issue by antonok-edm** [addr-rs/addr#6]
Thanks for this excellent library.

It appears `psl` has been causing the documentation on docs.rs for the `adblock` crate to fail to build for quite some time now. However, it looks like the documentation for both `psl` and `addr` build without issues. I'm curious if you have any insight as to what the difference might be.

Original issue reported here: https://github.com/brave/adblock-rust/issues/86

**Comment by Nemo157** [comment]
The reason the `psl` docs built fine is that they're from before the sandboxing was implemented. [Only since Oct 2019](https://blog.rust-lang.org/2019/09/18/upcoming-docsrs-changes.html) was the lack of network access enforced.

**Comment by antonok-edm** [comment]
@Nemo157 good find, that looks correct - I've added my +1 on the docs.rs issue

**Comment by john-consumable** [comment]
Is it possible to remove the network requirement to build addr?  It doesn't just effect docs.rs, it also effects people building offline and people using nix or other functional package managers to build their software.

**Comment by john-consumable** [comment]
Hm. Wait, I think I understand that using `$PSL_PATH` should make it unnecessary to go to the network, sorry for the noise!

**Comment by rushmorem** [comment]
Now fixed. `psl` 1.0.0 is now out and it no longer downloads the list during the build.
